version: "3.9"

# Создаем конейнер для обмена межу нашими контейнерами 
volumes:
  client-store:
    external: true

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}
        volumes:
          # подключаем контейнер обмена как папку ssr-store
          - client-store:/app/client/dist/ssr

    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
        volumes:
          # подключается папка из нашего репозитория, если пуста то будет пусто
          - ./packages/client/dist/:/client/dist/
          # подключаем контейнер обмена как папку /client
          - client-store:/client/dist/ssr2
        # добавляем зависимость от клиента, чтобы не собрался раньше него
        depends_on:
        - client
        - postgres

    postgres:
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data

